# Generated by Django 2.1 on 2020-09-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camapania',
            fields=[
                ('id_campania', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=500)),
                ('pregunta', models.TextField(max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('user_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
