# Generated by Django 2.1 on 2020-09-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20200906_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(max_length=500)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(max_length=500)),
                ('canal', models.TextField(max_length=20)),
                ('id_camapania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuesta.Campania')),
                ('id_contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='encuesta.Contacto')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='encuesta',
            unique_together={('id_contacto', 'id_camapania')},
        ),
    ]
