# Generated by Django 2.1 on 2020-09-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_auto_20200906_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuesta',
            old_name='id_camapania',
            new_name='id_campania',
        ),
        migrations.AlterUniqueTogether(
            name='encuesta',
            unique_together={('id_contacto', 'id_campania')},
        ),
    ]
